# **Analise do indice de Alfabetização do Brasil**

**Pipeline ETL & Data Quality**


Objetivo: Construir um pipeline de dados ponta-a-ponta, transformando dados "sujos" em um dataset pronto para treinamento de Machine Learning, utilizando a Arquitetura Medalhão (Bronze, Silver, Gold).

# Instalação de bibliotecas necessárias
!pip install pandas faker pyarrow fastparquet

**1. Configuração do Ambiente**

Realizar os imports necessários e validar as pastas para cada camada do cinturão de dados

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os

# Criando diretórios para organizar as camadas
os.makedirs('data/raw', exist_ok=True)
os.makedirs('data/bronze', exist_ok=True)
os.makedirs('data/silver', exist_ok=True)
os.makedirs('data/gold', exist_ok=True)

print("Ambiente configurado e pastas criadas!")

Ambiente configurado e pastas criadas!

# Ingestão na Camada Bronze

Ingestão das fontes de dados RAW para a camada bronze, em parquet, sem qualquer analise ou manupulação dos dados.

In [2]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_brasil.csv')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_brasil_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/meta_alfabetizacao_brasil.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/meta_alfabetizacao_brasil.parquet

(3, 13)

In [3]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_uf.csv')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_uf_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/meta_alfabetizacao_uf.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/meta_alfabetizacao_uf.parquet

(54, 14)

In [4]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_municipio.csv')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_municipio_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/meta_alfabetizacao_municipio.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/meta_alfabetizacao_municipio.parquet

(10704, 15)

In [5]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/br_inep_avaliacao_alfabetizacao_uf.csv')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'br_inep_avaliacao_alfabetizacao_uf_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/avaliacao_alfabetizacao_uf.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/avaliacao_alfabetizacao_uf.parquet

(145, 17)

In [6]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/br_inep_avaliacao_alfabetizacao_municipio.csv')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'br_inep_avaliacao_alfabetizacao_municipio_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/avaliacao_alfabetizacao_municipio.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/avaliacao_alfabetizacao_municipio.parquet

(23995, 17)

In [7]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2023/DADOS/TS_ALUNO.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2023_dados_ts_aluno_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2023_dados_ts_aluno.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2023_dados_ts_aluno.parquet

(1747439, 17)

In [8]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2024/DADOS/TS_ALUNO.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2024_dados_ts_aluno_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2024_dados_ts_aluno.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2024_dados_ts_aluno.parquet

(2120560, 17)

In [9]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2025/DADOS/TS_ALUNO.csv', sep=';', encoding='ISO-8859-1', low_memory=False)

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2025_dados_ts_aluno_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2025_dados_ts_aluno.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2025_dados_ts_aluno.parquet

(2222792, 29)

In [10]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2023/DADOS/TS_ESTADO.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2023_dados_ts_estado_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2023_dados_ts_estado.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2023_dados_ts_estado.parquet

(70, 9)

In [11]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2024/DADOS/TS_ESTADO.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2024_dados_ts_estado_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2024_dados_ts_estado.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2024_dados_ts_estado.parquet

(75, 18)

In [12]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2025/DADOS/TS_ESTADO.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2025_dados_ts_estado_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2025_dados_ts_estado.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2025_dados_ts_estado.parquet

(80, 18)

In [13]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2023/DADOS/TS_ITEM.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2023_dados_ts_item_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2023_dados_ts_item.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2023_dados_ts_item.parquet

(3443, 22)

In [14]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2024/DADOS/TS_ITEM.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2024_dados_ts_item_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2024_dados_ts_item.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2024_dados_ts_item.parquet

(1671, 22)

In [15]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2025/DADOS/TS_ITEM.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2025_dados_ts_item_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2025_dados_ts_item.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2025_dados_ts_item.parquet

(1960, 22)

In [16]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2023/DADOS/TS_MUNICIPIO.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2023_dados_ts_municipio_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2023_dados_ts_municipio.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2023_dados_ts_municipio.parquet

(11547, 11)

In [17]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2024/DADOS/TS_MUNICIPIO.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2024_dados_ts_municipio_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2024_dados_ts_municipio.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2024_dados_ts_municipio.parquet

(12448, 20)

In [18]:
def ingestao_bronze():
    # 1. Leitura do dado bruto (RAW)
    df = pd.read_csv('data/raw/microdados_AEEB_2025/DADOS/TS_MUNICIPIO.csv', sep=';', encoding='ISO-8859-1')

    # 2. Adição de Metadados
    df['_data_ingestao'] = datetime.now()
    df['_origem'] = 'microdados_AEEB_2025_dados_ts_municipio_csv'

    # 3. Salvamento em formato Colunar (Parquet)
    caminho_bronze = 'data/bronze/microdados_AEEB_2025_dados_ts_municipio.parquet'
    df.to_parquet(caminho_bronze, index=False)

    print(f"Ingestão Bronze concluída. Arquivo salvo em: {caminho_bronze}")
    return df

# Executando ingestão
df_bronze = ingestao_bronze()
df_bronze.shape

Ingestão Bronze concluída. Arquivo salvo em: data/bronze/microdados_AEEB_2025_dados_ts_municipio.parquet

(12416, 20)

# Validação de Qualidade e Camada Silver

Nesta etapa, os dados da camada Bronze são limpos, padronizados e validados.

Principais tratamentos:
- Padronização dos nomes das colunas
- Conversão de tipos
- Tratamento de valores ausentes
- Remoção de duplicidades
- Validação de anos, UFs, municípios e percentuais
- Separação de registros inválidos em quarentena

In [19]:
from pathlib import Path
from datetime import datetime
import pandas as pd
import unicodedata

BRONZE_PATH = Path("data/bronze")
SILVER_PATH = Path("data/silver")
QUARANTINE_PATH = SILVER_PATH / "quarantine"

SILVER_PATH.mkdir(parents=True, exist_ok=True)
QUARANTINE_PATH.mkdir(parents=True, exist_ok=True)

print("Diretórios da Silver criados com sucesso.")

Diretórios da Silver criados com sucesso.

Funções Auxiliares:

In [20]:
def normalizar_nome_coluna(coluna: str) -> str:
    coluna = coluna.strip().lower()
    coluna = unicodedata.normalize("NFKD", coluna)
    coluna = coluna.encode("ascii", errors="ignore").decode("utf-8")
    coluna = coluna.replace(" ", "_")
    coluna = coluna.replace("-", "_")
    coluna = coluna.replace("/", "_")
    coluna = coluna.replace("(", "")
    coluna = coluna.replace(")", "")
    return coluna


def padronizar_colunas(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df.columns = [normalizar_nome_coluna(coluna) for coluna in df.columns]
    return df


def limpar_strings(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    for coluna in df.select_dtypes(include=["object", 'str']).columns:
        df[coluna] = (
            df[coluna]
            .astype("string")
            .str.strip()
            .replace({"nan": None, "None": None, "": None})
        )

    return df

Função para padronizar campos comuns:

In [21]:
def padronizar_campos_comuns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    if "ano" in df.columns:
        df["ano"] = pd.to_numeric(df["ano"], errors="coerce").astype("Int64")

    if "sigla_uf" in df.columns:
        df["sigla_uf"] = (
            df["sigla_uf"]
            .astype(str)
            .str.strip()
            .str.upper()
            .replace({"NAN": None, "NONE": None, "": None})
        )

    if "id_municipio" in df.columns:
        df["id_municipio"] = (
            df["id_municipio"]
            .astype(str)
            .str.replace(".0", "", regex=False)
            .str.strip()
            .str.zfill(7)
            .replace({"0000nan": None, "000None": None})
        )

    for coluna in df.columns:
        nome_coluna = coluna.lower()

        if (
            "percentual" in nome_coluna
            or "meta" in nome_coluna
            or "taxa" in nome_coluna
            or "indicador" in nome_coluna
        ):
            df[coluna] = pd.to_numeric(df[coluna], errors="coerce")

    df["_data_processamento"] = datetime.now()
    df["_camada_origem"] = "bronze"

    return df

Função para separar válidos e inválidos:

Essa função não apaga os dados ruins diretamente. Ela separa os registros inválidos em uma pasta de quarentena.

In [22]:
def separar_validos_invalidos(df: pd.DataFrame, chaves_obrigatorias: list[str]):
    df = df.copy()
    condicao_invalida = pd.Series(False, index=df.index)

    for chave in chaves_obrigatorias:
        if chave in df.columns:
            condicao_invalida = condicao_invalida | df[chave].isna()
        else:
            print(f"Atenção: chave obrigatória não encontrada: {chave}")

    if "ano" in df.columns:
        condicao_invalida = condicao_invalida | df["ano"].isna()
        condicao_invalida = condicao_invalida | ~df["ano"].between(2023, 2030)

    if "sigla_uf" in df.columns:
        condicao_invalida = condicao_invalida | df["sigla_uf"].notna() & (df["sigla_uf"].str.len() != 2)

    if "id_municipio" in df.columns:
        condicao_invalida = condicao_invalida | df["id_municipio"].notna() & (df["id_municipio"].str.len() != 7)

    for coluna in df.columns:
        nome_coluna = coluna.lower()

        if (
            "percentual" in nome_coluna
            or "meta" in nome_coluna
            or "taxa" in nome_coluna
            or "indicador" in nome_coluna
        ):
            condicao_invalida = condicao_invalida | (
                df[coluna].notna() & ~df[coluna].between(0, 100)
            )

    validos = df[~condicao_invalida].copy()
    invalidos = df[condicao_invalida].copy()

    validos["_status_validacao"] = "valido"

    if not invalidos.empty:
        invalidos["_status_validacao"] = "invalido"

    return validos, invalidos

Função principal para processar uma tabela Bronze:

In [23]:
def processar_tabela_silver(
    nome_arquivo: str,
    chaves_obrigatorias: list[str],
    chave_deduplicacao: list[str]
):
    caminho_entrada = BRONZE_PATH / nome_arquivo

    if not caminho_entrada.exists():
        print(f"Arquivo não encontrado: {caminho_entrada}")
        return None

    df = pd.read_parquet(caminho_entrada)

    total_bronze = len(df)

    df = padronizar_colunas(df)
    df = limpar_strings(df)
    df = padronizar_campos_comuns(df)

    duplicados = pd.DataFrame()

    colunas_dedup_existentes = [
        coluna for coluna in chave_deduplicacao if coluna in df.columns
    ]

    if colunas_dedup_existentes:
        duplicados = df[df.duplicated(subset=colunas_dedup_existentes, keep=False)].copy()
        df = df.drop_duplicates(subset=colunas_dedup_existentes, keep="last")

    validos, invalidos = separar_validos_invalidos(df, chaves_obrigatorias)

    nome_base = nome_arquivo.replace(".parquet", "")
    caminho_saida = SILVER_PATH / f"silver_{nome_base}.parquet"

    validos.to_parquet(caminho_saida, index=False)

    if not invalidos.empty:
        invalidos.to_parquet(
            QUARANTINE_PATH / f"invalidos_{nome_base}.parquet",
            index=False
        )

    if not duplicados.empty:
        duplicados.to_parquet(
            QUARANTINE_PATH / f"duplicados_{nome_base}.parquet",
            index=False
        )

    resumo = {
        "arquivo": nome_arquivo,
        "total_bronze": total_bronze,
        "total_silver": len(validos),
        "total_invalidos": len(invalidos),
        "total_duplicados": len(duplicados),
        "saida": str(caminho_saida)
    }

    print(f"Processado: {nome_base}")
    print(f"Bronze: {total_bronze}")
    print(f"Silver válidos: {len(validos)}")
    print(f"Inválidos: {len(invalidos)}")
    print(f"Duplicados: {len(duplicados)}")
    print("-" * 50)

    return resumo

Processar suas tabelas Bronze:

In [24]:
resumos_silver = []

resumos_silver.append(
    processar_tabela_silver(
        nome_arquivo="meta_alfabetizacao_brasil.parquet",
        chaves_obrigatorias=["ano"],
        chave_deduplicacao=["ano"]
    )
)

resumos_silver.append(
    processar_tabela_silver(
        nome_arquivo="meta_alfabetizacao_uf.parquet",
        chaves_obrigatorias=["ano", "sigla_uf"],
        chave_deduplicacao=["ano", "sigla_uf"]
    )
)

resumos_silver.append(
    processar_tabela_silver(
        nome_arquivo="meta_alfabetizacao_municipio.parquet",
        chaves_obrigatorias=["ano", "id_municipio", "rede"],
        chave_deduplicacao=["ano", "id_municipio", "rede"]
    )
)

resumos_silver.append(
    processar_tabela_silver(
        nome_arquivo="avaliacao_alfabetizacao_uf.parquet",
        chaves_obrigatorias=["ano", "sigla_uf", "serie", "rede"],
        chave_deduplicacao=["ano", "sigla_uf", "serie", "rede"]
    )
)

resumos_silver.append(
    processar_tabela_silver(
        nome_arquivo="avaliacao_alfabetizacao_municipio.parquet",
        chaves_obrigatorias=["ano", "id_municipio", "serie", "rede"],
        chave_deduplicacao=["ano", "id_municipio", "serie", "rede"]
    )
)

resumos_silver = [resumo for resumo in resumos_silver if resumo is not None]

Processado: meta_alfabetizacao_brasil
Bronze: 3
Silver válidos: 3
Inválidos: 0
Duplicados: 0
--------------------------------------------------
Processado: meta_alfabetizacao_uf
Bronze: 54
Silver válidos: 54
Inválidos: 0
Duplicados: 0
--------------------------------------------------
Processado: meta_alfabetizacao_municipio
Bronze: 10704
Silver válidos: 10704
Inválidos: 0
Duplicados: 0
--------------------------------------------------
Processado: avaliacao_alfabetizacao_uf
Bronze: 145
Silver válidos: 145
Inválidos: 0
Duplicados: 0
--------------------------------------------------
Processado: avaliacao_alfabetizacao_municipio
Bronze: 23995
Silver válidos: 23995
Inválidos: 0
Duplicados: 0
--------------------------------------------------

Criar um resumo da Silver:

In [25]:
df_resumo_silver = pd.DataFrame(resumos_silver)
df_resumo_silver

df_resumo_silver.to_csv(SILVER_PATH / "resumo_processamento_silver.csv", index=False)

list(SILVER_PATH.glob("*.parquet"))
list(QUARANTINE_PATH.glob("*.parquet"))

df_silver_municipio = pd.read_parquet(
    SILVER_PATH / "silver_avaliacao_alfabetizacao_municipio.parquet"
)

df_silver_municipio.head()
df_silver_municipio.info()
df_silver_municipio.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 23995 entries, 0 to 23994
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ano                      23995 non-null  Int64
 1   id_municipio             23995 non-null  str
 2   serie                    23995 non-null  int64
 3   rede                     23995 non-null  int64
 4   taxa_alfabetizacao       23995 non-null  float64
 5   media_portugues          23995 non-null  float64
 6   proporcao_aluno_nivel_0  12448 non-null  float64
 7   proporcao_aluno_nivel_1  12448 non-null  float64
 8   proporcao_aluno_nivel_2  12448 non-null  float64
 9   proporcao_aluno_nivel_3  12448 non-null  float64
 10  proporcao_aluno_nivel_4  12448 non-null  float64
 11  proporcao_aluno_nivel_5  12448 non-null  float64
 12  proporcao_aluno_nivel_6  12448 non-null  float64
 13  proporcao_aluno_nivel_7  12448 non-null  float64
 14  proporcao_aluno_nivel_8  12448 non-null  float64
 15  _data_ingestao           23995 non-null  datetime64[us]
 16  _origem                  23995 non-null  string
 17  _data_processamento      23995 non-null  datetime64[us]
 18  _camada_origem           23995 non-null  str
 19  _status_validacao        23995 non-null  str
dtypes: Int64(1), datetime64[us](2), float64(11), int64(2), str(3), string(1)
memory usage: 5.1 MB

ano                            0
id_municipio                   0
serie                          0
rede                           0
taxa_alfabetizacao             0
media_portugues                0
proporcao_aluno_nivel_0    11547
proporcao_aluno_nivel_1    11547
proporcao_aluno_nivel_2    11547
proporcao_aluno_nivel_3    11547
proporcao_aluno_nivel_4    11547
proporcao_aluno_nivel_5    11547
proporcao_aluno_nivel_6    11547
proporcao_aluno_nivel_7    11547
proporcao_aluno_nivel_8    11547
_data_ingestao                 0
_origem                        0
_data_processamento            0
_camada_origem                 0
_status_validacao              0
dtype: int64

Criar uma tabela integrada municipal na Silver:

In [26]:
print("Etapa 1/9: lendo as bases Silver de metas e avaliacao municipais...")
meta_municipio = pd.read_parquet(
    SILVER_PATH / "silver_meta_alfabetizacao_municipio.parquet"
)
avaliacao_municipio = pd.read_parquet(
    SILVER_PATH / "silver_avaliacao_alfabetizacao_municipio.parquet"
)

print("Etapa 2/9: padronizando chaves de integracao (ano, id_municipio e rede)...")
mapa_rede = {
    "1": "federal",
    "2": "estadual",
    "3": "municipal",
    "4": "privada",
    "5": "publica",
    "6": "publica",
    "pública": "publica",
    "publica": "publica",
    "municipal": "municipal",
    "estadual": "estadual",
    "federal": "federal",
    "privada": "privada"
}

for df in [meta_municipio, avaliacao_municipio]:
    df["ano"] = pd.to_numeric(df["ano"], errors="coerce").astype("Int64")
    df["id_municipio"] = (
        df["id_municipio"]
        .astype("string")
        .str.replace(".0", "", regex=False)
        .str.strip()
        .str.zfill(7)
    )
    df["rede"] = (
        df["rede"]
        .astype("string")
        .str.strip()
        .str.lower()
        .replace(mapa_rede)
    )

print("Etapa 3/9: identificando colunas de meta por ano...")
colunas_meta_ano = sorted(
    [col for col in meta_municipio.columns if col.startswith("meta_alfabetizacao_")]
 )

if not colunas_meta_ano:
    raise ValueError("Nenhuma coluna de meta por ano foi encontrada em meta_municipio.")

print(f"Colunas detectadas: {colunas_meta_ano}")
print("Etapa 4/9: transformando metas do formato largo para formato anual...")
id_vars = [
    col for col in ["id_municipio", "rede", "ano", "taxa_alfabetizacao"]
    if col in meta_municipio.columns
]

metas_por_ano_municipio = (
    meta_municipio
    .melt(
        id_vars=id_vars,
        value_vars=colunas_meta_ano,
        var_name="coluna_meta",
        value_name="meta_alfabetizacao"
    )
)

print("Etapa 5/9: extraindo o ano da meta e ajustando tipos...")
metas_por_ano_municipio["ano_meta"] = (
    metas_por_ano_municipio["coluna_meta"]
    .str.extract(r"(\d{4})", expand=False)
    .astype("Int64")
)
metas_por_ano_municipio["meta_alfabetizacao"] = pd.to_numeric(
    metas_por_ano_municipio["meta_alfabetizacao"], errors="coerce"
)

print("Etapa 6/9: limpando nulos e deixando apenas uma meta por municipio, rede e ano...")
metas_por_ano_municipio = (
    metas_por_ano_municipio
    .drop(columns=["coluna_meta"])
    .dropna(subset=["meta_alfabetizacao", "ano_meta"])
    .rename(columns={"taxa_alfabetizacao": "taxa_alfabetizacao_meta_base"})
    .drop_duplicates(subset=["id_municipio", "rede", "ano_meta"], keep="last")
    .sort_values(["id_municipio", "rede", "ano_meta"])
    .reset_index(drop=True)
)

print("Etapa 7/9: fazendo o join entre avaliacao e metas por municipio, rede e ano...")
avaliacao_para_merge = avaliacao_municipio.copy()
avaliacao_para_merge["ano_meta"] = avaliacao_para_merge["ano"]

silver_indicador_municipio = avaliacao_para_merge.merge(
    metas_por_ano_municipio[[
        "id_municipio",
        "rede",
        "ano_meta",
        "meta_alfabetizacao",
        "taxa_alfabetizacao_meta_base"
    ]],
    on=["id_municipio", "rede", "ano_meta"],
    how="left"
)

print("Etapa 8/9: adicionando metadados e salvando a tabela integrada...")
silver_indicador_municipio["_data_processamento"] = datetime.now()
silver_indicador_municipio["_camada_origem"] = "silver"

silver_indicador_municipio.to_parquet(
    SILVER_PATH / "silver_indicador_municipio.parquet",
    index=False
)

print("Etapa 9/9: validando a pergunta 'quero saber as metas de municipio por ano'...")
metas_municipio_por_ano = (
    silver_indicador_municipio[["id_municipio", "rede", "ano_meta", "meta_alfabetizacao"]]
    .dropna(subset=["meta_alfabetizacao"])
    .drop_duplicates()
    .sort_values(["ano_meta", "id_municipio", "rede"])
    .reset_index(drop=True)
)

print(f"Linhas avaliacao: {len(avaliacao_municipio):,}")
print(f"Linhas metas anuais: {len(metas_por_ano_municipio):,}")
print(f"Linhas tabela integrada: {len(silver_indicador_municipio):,}")
print("\nPercentual com meta encontrada:")
print((silver_indicador_municipio["meta_alfabetizacao"].notna().mean() * 100).round(2), "%")
print("\nQuantidade de metas por ano:")
print(metas_municipio_por_ano.groupby("ano_meta").size())

metas_municipio_por_ano.head(20)

Etapa 1/9: lendo as bases Silver de metas e avaliacao municipais...
Etapa 2/9: padronizando chaves de integracao (ano, id_municipio e rede)...
Etapa 3/9: identificando colunas de meta por ano...
Colunas detectadas: ['meta_alfabetizacao_2024', 'meta_alfabetizacao_2025', 'meta_alfabetizacao_2026', 'meta_alfabetizacao_2027', 'meta_alfabetizacao_2028', 'meta_alfabetizacao_2029', 'meta_alfabetizacao_2030']
Etapa 4/9: transformando metas do formato largo para formato anual...
Etapa 5/9: extraindo o ano da meta e ajustando tipos...
Etapa 6/9: limpando nulos e deixando apenas uma meta por municipio, rede e ano...
Etapa 7/9: fazendo o join entre avaliacao e metas por municipio, rede e ano...
Etapa 8/9: adicionando metadados e salvando a tabela integrada...
Etapa 9/9: validando a pergunta 'quero saber as metas de municipio por ano'...
Linhas avaliacao: 23,995
Linhas metas anuais: 37,344
Linhas tabela integrada: 23,995

Percentual com meta encontrada:
21.8 %

Quantidade de metas por ano:
ano_meta
2024    5232
dtype: int64

   id_municipio       rede  ano_meta  meta_alfabetizacao
0       1100015  municipal      2024               67.08
1       1100023  municipal      2024               65.22
2       1100031  municipal      2024               70.85
3       1100049  municipal      2024               65.39
4       1100056  municipal      2024               62.09
5       1100064  municipal      2024               65.67
6       1100072  municipal      2024               61.82
7       1100080  municipal      2024               80.00
8       1100098  municipal      2024               80.00
9       1100106  municipal      2024               47.82
10      1100114  municipal      2024               65.65
11      1100122  municipal      2024               80.00
12      1100130  municipal      2024               56.12
13      1100148  municipal      2024               75.60
14      1100155  municipal      2024               73.58
15      1100189  municipal      2024               71.37
16      1100205  municipal      2024               67.50
17      1100254  municipal      2024               65.31
18      1100262  municipal      2024               80.00
19      1100288  municipal      2024               70.60

Análise Metas Municipio

In [27]:
print("Avaliação - rede:")
print(avaliacao_municipio["rede"].value_counts(dropna=False))

print("\nMeta - rede:")
print(meta_municipio["rede"].value_counts(dropna=False))

print("\nAvaliação - anos:")
print(avaliacao_municipio["ano"].value_counts(dropna=False).sort_index())

print("\nMeta - anos:")
print(meta_municipio["ano"].value_counts(dropna=False).sort_index())

chaves_avaliacao = avaliacao_municipio[["ano", "id_municipio", "rede"]].drop_duplicates()
chaves_meta = meta_municipio[["ano", "id_municipio", "rede"]].drop_duplicates()

chaves_em_comum = chaves_avaliacao.merge(
    chaves_meta,
    on=["ano", "id_municipio", "rede"],
    how="inner"
)

print("Chaves avaliação:", len(chaves_avaliacao))
print("Chaves meta:", len(chaves_meta))
print("Chaves em comum:", len(chaves_em_comum))

Avaliação - rede:
rede
municipal    10896
publica      10466
estadual      2235
0              398
Name: count, dtype: int64[pyarrow]

Meta - rede:
rede
municipal    10704
Name: count, dtype: int64[pyarrow]

Avaliação - anos:
ano
2023    11547
2024    12448
Name: count, dtype: Int64

Meta - anos:
ano
2023    5352
2024    5352
Name: count, dtype: Int64
Chaves avaliação: 23995
Chaves meta: 10704
Chaves em comum: 10654

Criar uma tabela integrada estadual na Silver:

In [28]:
meta_uf = pd.read_parquet(
    SILVER_PATH / "silver_meta_alfabetizacao_uf.parquet"
)

avaliacao_uf = pd.read_parquet(
    SILVER_PATH / "silver_avaliacao_alfabetizacao_uf.parquet"
)

silver_indicador_uf = avaliacao_uf.merge(
    meta_uf,
    on=["ano", "sigla_uf"],
    how="left",
    suffixes=("_avaliacao", "_meta")
)

silver_indicador_uf["_data_processamento"] = datetime.now()
silver_indicador_uf["_camada_origem"] = "silver"

silver_indicador_uf.to_parquet(
    SILVER_PATH / "silver_indicador_uf.parquet",
    index=False
)

silver_indicador_uf.head()

,ano,sigla_uf,serie,rede_avaliacao,taxa_alfabetizacao_avaliacao,media_portugues,proporcao_aluno_nivel_0,proporcao_aluno_nivel_1,proporcao_aluno_nivel_2,proporcao_aluno_nivel_3,...,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao,_data_ingestao_meta,_origem_meta,_data_processamento_meta,_camada_origem_meta,_status_validacao_meta,_data_processamento,_camada_origem
0,2023,AM,2,3,49.20,733.6637,NaN,NaN,NaN,NaN,...,76.9,80.0,76.14,2026-07-10 15:57:13.633734,br_inep_avaliacao_alfabetizacao_meta_alfabetiz...,2026-07-10 15:57:35.595939,bronze,valido,2026-07-10 15:57:36.066501,silver
1,2023,PB,2,2,55.23,744.8152,NaN,NaN,NaN,NaN,...,76.8,80.0,88.22,2026-07-10 15:57:13.633734,br_inep_avaliacao_alfabetizacao_meta_alfabetiz...,2026-07-10 15:57:35.595939,bronze,valido,2026-07-10 15:57:36.066501,silver
2,2023,PR,2,5,73.12,757.2146,NaN,NaN,NaN,NaN,...,79.1,80.0,86.18,2026-07-10 15:57:13.633734,br_inep_avaliacao_alfabetizacao_meta_alfabetiz...,2026-07-10 15:57:35.595939,bronze,valido,2026-07-10 15:57:36.066501,silver
3,2023,AP,2,3,41.87,732.7858,NaN,NaN,NaN,NaN,...,75.8,80.0,89.68,2026-07-10 15:57:13.633734,br_inep_avaliacao_alfabetizacao_meta_alfabetiz...,2026-07-10 15:57:35.595939,bronze,valido,2026-07-10 15:57:36.066501,silver
4,2023,PE,2,5,58.95,747.4522,NaN,NaN,NaN,NaN,...,77.6,80.0,91.93,2026-07-10 15:57:13.633734,br_inep_avaliacao_alfabetizacao_meta_alfabetiz...,2026-07-10 15:57:35.595939,bronze,valido,2026-07-10 15:57:36.066501,silver

13. Validações finais da Silver

In [29]:
def diagnostico_tabela(df: pd.DataFrame, nome_tabela: str):
    print(f"Diagnóstico: {nome_tabela}")
    print(f"Total de linhas: {len(df)}")
    print(f"Total de colunas: {len(df.columns)}")
    print("\nValores ausentes:")
    print(df.isna().sum())
    print("\nDuplicados:")
    print(df.duplicated().sum())
    print("-" * 50)
diagnostico_tabela(silver_indicador_municipio, "silver_indicador_municipio")
diagnostico_tabela(silver_indicador_uf, "silver_indicador_uf")

Diagnóstico: silver_indicador_municipio
Total de linhas: 23995
Total de colunas: 23

Valores ausentes:
ano                                 0
id_municipio                        0
serie                               0
rede                                0
taxa_alfabetizacao                  0
media_portugues                     0
proporcao_aluno_nivel_0         11547
proporcao_aluno_nivel_1         11547
proporcao_aluno_nivel_2         11547
proporcao_aluno_nivel_3         11547
proporcao_aluno_nivel_4         11547
proporcao_aluno_nivel_5         11547
proporcao_aluno_nivel_6         11547
proporcao_aluno_nivel_7         11547
proporcao_aluno_nivel_8         11547
_data_ingestao                      0
_origem                             0
_data_processamento                 0
_camada_origem                      0
_status_validacao                   0
ano_meta                            0
meta_alfabetizacao              18763
taxa_alfabetizacao_meta_base    18763
dtype: int64

Duplicados:
0
--------------------------------------------------
Diagnóstico: silver_indicador_uf
Total de linhas: 145
Total de colunas: 37

Valores ausentes:
ano                               0
sigla_uf                          0
serie                             0
rede_avaliacao                    0
taxa_alfabetizacao_avaliacao      0
media_portugues                   0
proporcao_aluno_nivel_0          70
proporcao_aluno_nivel_1          70
proporcao_aluno_nivel_2          70
proporcao_aluno_nivel_3          70
proporcao_aluno_nivel_4          70
proporcao_aluno_nivel_5          70
proporcao_aluno_nivel_6          70
proporcao_aluno_nivel_7          70
proporcao_aluno_nivel_8          70
_data_ingestao_avaliacao          0
_origem_avaliacao                 0
_data_processamento_avaliacao     0
_camada_origem_avaliacao          0
_status_validacao_avaliacao       0
rede_meta                         0
taxa_alfabetizacao_meta           0
meta_alfabetizacao_2024           3
meta_alfabetizacao_2025           0
meta_alfabetizacao_2026           0
meta_alfabetizacao_2027           0
meta_alfabetizacao_2028           0
meta_alfabetizacao_2029           0
meta_alfabetizacao_2030           0
percentual_participacao           0
_data_ingestao_meta               0
_origem_meta                      0
_data_processamento_meta          0
_camada_origem_meta               0
_status_validacao_meta            0
_data_processamento               0
_camada_origem                    0
dtype: int64

Duplicados:
0
--------------------------------------------------

# Gold Layer — Camada Analítica

Nesta etapa, os dados tratados da camada Silver são transformados em datasets analíticos prontos para consumo por dashboards, análises estatísticas e modelos de Machine Learning.

Principais objetivos:
- Consolidar indicadores por município e UF
- Comparar resultados observados com metas de alfabetização
- Calcular gap em relação à meta
- Classificar municípios conforme atingimento da meta
- Preparar dataset para aplicações de IA

Configuração da Gold

In [30]:
from pathlib import Path
from datetime import datetime
import pandas as pd
import numpy as np

SILVER_PATH = Path("data/silver")
GOLD_PATH = Path("data/gold")

GOLD_PATH.mkdir(parents=True, exist_ok=True)

print("Diretório Gold criado com sucesso.")

Diretório Gold criado com sucesso.

Ler as tabelas Silver

In [31]:
silver_indicador_municipio = pd.read_parquet(
    SILVER_PATH / "silver_indicador_municipio.parquet"
)

silver_indicador_uf = pd.read_parquet(
    SILVER_PATH / "silver_indicador_uf.parquet"
)

print("Município:", silver_indicador_municipio.shape)
print("UF:", silver_indicador_uf.shape)

Município: (23995, 23)
UF: (145, 37)

Inspecionar colunas antes da Gold

In [32]:
print("Colunas município:")
print(silver_indicador_municipio.columns.tolist())

print("\nColunas UF:")
print(silver_indicador_uf.columns.tolist())

Colunas município:
['ano', 'id_municipio', 'serie', 'rede', 'taxa_alfabetizacao', 'media_portugues', 'proporcao_aluno_nivel_0', 'proporcao_aluno_nivel_1', 'proporcao_aluno_nivel_2', 'proporcao_aluno_nivel_3', 'proporcao_aluno_nivel_4', 'proporcao_aluno_nivel_5', 'proporcao_aluno_nivel_6', 'proporcao_aluno_nivel_7', 'proporcao_aluno_nivel_8', '_data_ingestao', '_origem', '_data_processamento', '_camada_origem', '_status_validacao', 'ano_meta', 'meta_alfabetizacao', 'taxa_alfabetizacao_meta_base']

Colunas UF:
['ano', 'sigla_uf', 'serie', 'rede_avaliacao', 'taxa_alfabetizacao_avaliacao', 'media_portugues', 'proporcao_aluno_nivel_0', 'proporcao_aluno_nivel_1', 'proporcao_aluno_nivel_2', 'proporcao_aluno_nivel_3', 'proporcao_aluno_nivel_4', 'proporcao_aluno_nivel_5', 'proporcao_aluno_nivel_6', 'proporcao_aluno_nivel_7', 'proporcao_aluno_nivel_8', '_data_ingestao_avaliacao', '_origem_avaliacao', '_data_processamento_avaliacao', '_camada_origem_avaliacao', '_status_validacao_avaliacao', 'rede_meta', 'taxa_alfabetizacao_meta', 'meta_alfabetizacao_2024', 'meta_alfabetizacao_2025', 'meta_alfabetizacao_2026', 'meta_alfabetizacao_2027', 'meta_alfabetizacao_2028', 'meta_alfabetizacao_2029', 'meta_alfabetizacao_2030', 'percentual_participacao', '_data_ingestao_meta', '_origem_meta', '_data_processamento_meta', '_camada_origem_meta', '_status_validacao_meta', '_data_processamento', '_camada_origem']

Função para identificar coluna de resultado

In [33]:
def encontrar_coluna(df, candidatos):
    for coluna in candidatos:
        if coluna in df.columns:
            return coluna
    return None

coluna_resultado_municipio = encontrar_coluna(
    silver_indicador_municipio,
    [
        "taxa_alfabetizacao",
        "taxa_alfabetizacao_avaliacao",
        "percentual_alfabetizacao",
        "percentual_alfabetizados",
        "indicador_alfabetizacao"
    ]
)

coluna_meta_municipio = encontrar_coluna(
    silver_indicador_municipio,
    [
        "meta_alfabetizacao",
        "meta_ano_avaliacao",
        "meta"
    ]
)

print("Coluna resultado município:", coluna_resultado_municipio)
print("Coluna meta município:", coluna_meta_municipio)

Coluna resultado município: taxa_alfabetizacao
Coluna meta município: meta_alfabetizacao

Criar gold_indicador_municipio

Essa tabela deve ter colunas finais, limpas e úteis para análise.

In [34]:
gold_indicador_municipio = silver_indicador_municipio.copy()

# Garantir tipos
gold_indicador_municipio["ano"] = pd.to_numeric(
    gold_indicador_municipio["ano"],
    errors="coerce"
).astype("Int64")

gold_indicador_municipio["id_municipio"] = (
    gold_indicador_municipio["id_municipio"]
    .astype("string")
    .str.zfill(7)
)

gold_indicador_municipio["rede"] = (
    gold_indicador_municipio["rede"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Criar colunas padronizadas para resultado e meta
if coluna_resultado_municipio:
    gold_indicador_municipio["resultado_alfabetizacao"] = pd.to_numeric(
        gold_indicador_municipio[coluna_resultado_municipio],
        errors="coerce"
    )

if coluna_meta_municipio:
    gold_indicador_municipio["meta_alfabetizacao"] = pd.to_numeric(
        gold_indicador_municipio[coluna_meta_municipio],
        errors="coerce"
    )

# Calcular gap
gold_indicador_municipio["gap_meta"] = (
    gold_indicador_municipio["resultado_alfabetizacao"]
    - gold_indicador_municipio["meta_alfabetizacao"]
)

# Classificar status
gold_indicador_municipio["status_meta"] = np.where(
    gold_indicador_municipio["gap_meta"].isna(),
    "sem_meta_disponivel",
    np.where(
        gold_indicador_municipio["gap_meta"] >= 0,
        "atingiu_meta",
        "abaixo_meta"
    )
)

# Criar classificação de risco
gold_indicador_municipio["classificacao_risco"] = np.select(
    [
        gold_indicador_municipio["gap_meta"].isna(),
        gold_indicador_municipio["gap_meta"] >= 0,
        gold_indicador_municipio["gap_meta"] >= -5,
        gold_indicador_municipio["gap_meta"] >= -10,
        gold_indicador_municipio["gap_meta"] < -10
    ],
    [
        "sem_meta",
        "baixo_risco",
        "atencao",
        "risco_moderado",
        "alto_risco"
    ],
    default="sem_classificacao"
)

gold_indicador_municipio["_data_processamento_gold"] = datetime.now()
gold_indicador_municipio["_camada_origem"] = "silver"

gold_indicador_municipio.to_parquet(
    GOLD_PATH / "gold_indicador_municipio.parquet",
    index=False
)

gold_indicador_municipio.head()

,ano,id_municipio,serie,rede,taxa_alfabetizacao,media_portugues,proporcao_aluno_nivel_0,proporcao_aluno_nivel_1,proporcao_aluno_nivel_2,proporcao_aluno_nivel_3,...,_camada_origem,_status_validacao,ano_meta,meta_alfabetizacao,taxa_alfabetizacao_meta_base,resultado_alfabetizacao,gap_meta,status_meta,classificacao_risco,_data_processamento_gold
0,2023,1100031,2,municipal,69.10,767.8763,NaN,NaN,NaN,NaN,...,silver,valido,2023,NaN,NaN,69.10,NaN,sem_meta_disponivel,sem_meta,2026-07-10 15:57:36.198786
1,2023,1100072,2,municipal,58.20,747.8918,NaN,NaN,NaN,NaN,...,silver,valido,2023,NaN,NaN,58.20,NaN,sem_meta_disponivel,sem_meta,2026-07-10 15:57:36.198786
2,2023,1100189,2,publica,69.73,762.4062,NaN,NaN,NaN,NaN,...,silver,valido,2023,NaN,NaN,69.73,NaN,sem_meta_disponivel,sem_meta,2026-07-10 15:57:36.198786
3,2023,1101609,2,municipal,50.70,745.6802,NaN,NaN,NaN,NaN,...,silver,valido,2023,NaN,NaN,50.70,NaN,sem_meta_disponivel,sem_meta,2026-07-10 15:57:36.198786
4,2023,1101807,2,municipal,55.69,752.3724,NaN,NaN,NaN,NaN,...,silver,valido,2023,NaN,NaN,55.69,NaN,sem_meta_disponivel,sem_meta,2026-07-10 15:57:36.198786

In [46]:
print(
    gold_indicador_municipio
    .groupby(["ano", "rede"])["meta_alfabetizacao"]
    .apply(lambda x: x.notna().sum())
)

print(
    gold_indicador_municipio
    .groupby(["ano", "rede"])["status_meta"]
    .value_counts(dropna=False)
)

ano   rede
2023  estadual        0
      municipal       0
      publica         0
2024  0               0
      estadual        0
      municipal    5232
      publica         0
Name: meta_alfabetizacao, dtype: int64
ano   rede       status_meta
2023  estadual   sem_meta_disponivel    1149
      municipal  sem_meta_disponivel    5448
      publica    sem_meta_disponivel    4950
2024  0          sem_meta_disponivel     398
      estadual   sem_meta_disponivel    1086
      municipal  atingiu_meta           2788
                 abaixo_meta            2444
                 sem_meta_disponivel     216
      publica    sem_meta_disponivel    5516
Name: count, dtype: int64

Criar gold_comparativo_meta_resultado

Essa é uma das tabelas mais importantes para o trabalho, porque responde diretamente:

> Quais municípios estão acima ou abaixo da meta?

In [35]:
colunas_comparativo = [
    coluna for coluna in [
        "ano",
        "ano_meta",
        "id_municipio",
        "nome_municipio",
        "sigla_uf",
        "rede",
        "serie",
        "resultado_alfabetizacao",
        "meta_alfabetizacao",
        "gap_meta",
        "status_meta",
        "classificacao_risco"
    ]
    if coluna in gold_indicador_municipio.columns
]

gold_comparativo_meta_resultado = gold_indicador_municipio[colunas_comparativo].copy()

gold_comparativo_meta_resultado = gold_comparativo_meta_resultado.sort_values(
    by=["ano", "sigla_uf", "id_municipio"] if "sigla_uf" in gold_comparativo_meta_resultado.columns else ["ano", "id_municipio"]
)

gold_comparativo_meta_resultado.to_parquet(
    GOLD_PATH / "gold_comparativo_meta_resultado.parquet",
    index=False
)

gold_comparativo_meta_resultado.head()

,ano,ano_meta,id_municipio,rede,serie,resultado_alfabetizacao,meta_alfabetizacao,gap_meta,status_meta,classificacao_risco
6493,2023,2023,1100015,municipal,2,64.55,NaN,NaN,sem_meta_disponivel,sem_meta
6957,2023,2023,1100015,publica,2,64.55,NaN,NaN,sem_meta_disponivel,sem_meta
1130,2023,2023,1100023,publica,2,62.30,NaN,NaN,sem_meta_disponivel,sem_meta
8318,2023,2023,1100023,municipal,2,62.30,NaN,NaN,sem_meta_disponivel,sem_meta
0,2023,2023,1100031,municipal,2,69.10,NaN,NaN,sem_meta_disponivel,sem_meta

Criar gold_indicador_uf

In [48]:
gold_indicador_uf = silver_indicador_uf.copy()

gold_indicador_uf["resultado_alfabetizacao"] = pd.to_numeric(
    gold_indicador_uf["taxa_alfabetizacao_avaliacao"],
    errors="coerce"
)

gold_indicador_uf["meta_alfabetizacao"] = gold_indicador_uf.apply(
    lambda row: row.get(f"meta_alfabetizacao_{int(row['ano'])}", pd.NA)
    if pd.notna(row["ano"]) else pd.NA,
    axis=1
)

gold_indicador_uf["gap_meta"] = (
    gold_indicador_uf["resultado_alfabetizacao"]
    - gold_indicador_uf["meta_alfabetizacao"]
)

gold_indicador_uf["status_meta"] = np.where(
    gold_indicador_uf["gap_meta"].isna(),
    "sem_meta_disponivel",
    np.where(gold_indicador_uf["gap_meta"] >= 0, "atingiu_meta", "abaixo_meta")
)

gold_indicador_uf.to_parquet(
    GOLD_PATH / "gold_indicador_uf.parquet",
    index=False
)

Criar gold_dataset_ia_municipio

Essa tabela deve ser pensada para machine learning. Não precisa treinar modelo agora; o PDF pede explicar como a Gold poderia ser usada para predição de alfabetização, desigualdade educacional e políticas públicas baseadas em dados.

In [37]:
colunas_ia = [
    coluna for coluna in [
        "ano",
        "id_municipio",
        "nome_municipio",
        "sigla_uf",
        "rede",
        "serie",
        "resultado_alfabetizacao",
        "meta_alfabetizacao",
        "gap_meta",
        "status_meta",
        "classificacao_risco",
        "percentual_participacao",
        "nivel_alfabetizacao"
    ]
    if coluna in gold_indicador_municipio.columns
]

gold_dataset_ia_municipio = gold_indicador_municipio[colunas_ia].copy()

# Exemplo de variável alvo para modelo de classificação
gold_dataset_ia_municipio["target_atingiu_meta"] = np.where(
    gold_dataset_ia_municipio["status_meta"] == "atingiu_meta",
    1,
    np.where(
        gold_dataset_ia_municipio["status_meta"] == "abaixo_meta",
        0,
        pd.NA
    )
)

gold_dataset_ia_municipio.to_parquet(
    GOLD_PATH / "gold_dataset_ia_municipio.parquet",
    index=False
)

gold_dataset_ia_municipio.head()

,ano,id_municipio,rede,serie,resultado_alfabetizacao,meta_alfabetizacao,gap_meta,status_meta,classificacao_risco,target_atingiu_meta
0,2023,1100031,municipal,2,69.10,NaN,NaN,sem_meta_disponivel,sem_meta,<NA>
1,2023,1100072,municipal,2,58.20,NaN,NaN,sem_meta_disponivel,sem_meta,<NA>
2,2023,1100189,publica,2,69.73,NaN,NaN,sem_meta_disponivel,sem_meta,<NA>
3,2023,1101609,municipal,2,50.70,NaN,NaN,sem_meta_disponivel,sem_meta,<NA>
4,2023,1101807,municipal,2,55.69,NaN,NaN,sem_meta_disponivel,sem_meta,<NA>

Criar resumo da Gold

In [44]:
resumo_gold = pd.DataFrame([
    {
        "arquivo": "gold_indicador_municipio.parquet",
        "linhas": len(gold_indicador_municipio),
        "colunas": len(gold_indicador_municipio.columns),
        "descricao": "Indicadores analíticos por município, ano, rede e série"
    },
    {
        "arquivo": "gold_indicador_uf.parquet",
        "linhas": len(gold_indicador_uf),
        "colunas": len(gold_indicador_uf.columns),
        "descricao": "Indicadores agregados por UF"
    },
    {
        "arquivo": "gold_comparativo_meta_resultado.parquet",
        "linhas": len(gold_comparativo_meta_resultado),
        "colunas": len(gold_comparativo_meta_resultado.columns),
        "descricao": "Comparação entre resultado observado e meta"
    },
    {
        "arquivo": "gold_dataset_ia_municipio.parquet",
        "linhas": len(gold_dataset_ia_municipio),
        "colunas": len(gold_dataset_ia_municipio.columns),
        "descricao": "Dataset preparado para aplicações de IA"
    }
])

resumo_gold.to_csv(GOLD_PATH / "resumo_gold.csv", index=False)

resumo_gold

,arquivo,linhas,colunas,descricao
0,gold_indicador_municipio.parquet,23995,28,"Indicadores analíticos por município, ano, red..."
1,gold_indicador_uf.parquet,145,41,Indicadores agregados por UF
2,gold_comparativo_meta_resultado.parquet,23995,10,Comparação entre resultado observado e meta
3,gold_dataset_ia_municipio.parquet,23995,10,Dataset preparado para aplicações de IA

Validações da Gold

In [45]:
def diagnostico_gold(df: pd.DataFrame, nome_tabela: str):
    print(f"Diagnóstico Gold: {nome_tabela}")
    print(f"Linhas: {len(df)}")
    print(f"Colunas: {len(df.columns)}")
    print("\nDuplicados:")
    print(df.duplicated().sum())
    print("\nValores ausentes principais:")
    print(df.isna().sum().sort_values(ascending=False).head(15))
    print("-" * 80)

diagnostico_gold(gold_indicador_municipio, "gold_indicador_municipio")
diagnostico_gold(gold_indicador_uf, "gold_indicador_uf")
diagnostico_gold(gold_comparativo_meta_resultado, "gold_comparativo_meta_resultado")
diagnostico_gold(gold_dataset_ia_municipio, "gold_dataset_ia_municipio")


print("Distribuição status_meta:")
print(gold_indicador_municipio["status_meta"].value_counts(dropna=False))

print("\nDistribuição classificação de risco:")
print(gold_indicador_municipio["classificacao_risco"].value_counts(dropna=False))

print("\nGap meta:")
print(gold_indicador_municipio["gap_meta"].describe())

Diagnóstico Gold: gold_indicador_municipio
Linhas: 23995
Colunas: 28

Duplicados:
0

Valores ausentes principais:
gap_meta                        18763
meta_alfabetizacao              18763
taxa_alfabetizacao_meta_base    18763
proporcao_aluno_nivel_2         11547
proporcao_aluno_nivel_4         11547
proporcao_aluno_nivel_5         11547
proporcao_aluno_nivel_7         11547
proporcao_aluno_nivel_8         11547
proporcao_aluno_nivel_6         11547
proporcao_aluno_nivel_3         11547
proporcao_aluno_nivel_0         11547
proporcao_aluno_nivel_1         11547
media_portugues                     0
taxa_alfabetizacao                  0
serie                               0
dtype: int64
--------------------------------------------------------------------------------
Diagnóstico Gold: gold_indicador_uf
Linhas: 145
Colunas: 41

Duplicados:
0

Valores ausentes principais:
gap_meta                   73
meta_alfabetizacao         73
proporcao_aluno_nivel_2    70
proporcao_aluno_nivel_0    70
proporcao_aluno_nivel_7    70
proporcao_aluno_nivel_4    70
proporcao_aluno_nivel_3    70
proporcao_aluno_nivel_8    70
proporcao_aluno_nivel_1    70
proporcao_aluno_nivel_5    70
proporcao_aluno_nivel_6    70
meta_alfabetizacao_2024     3
serie                       0
sigla_uf                    0
ano                         0
dtype: int64
--------------------------------------------------------------------------------
Diagnóstico Gold: gold_comparativo_meta_resultado
Linhas: 23995
Colunas: 10

Duplicados:
0

Valores ausentes principais:
meta_alfabetizacao         18763
gap_meta                   18763
ano_meta                       0
ano                            0
id_municipio                   0
rede                           0
resultado_alfabetizacao        0
serie                          0
status_meta                    0
classificacao_risco            0
dtype: int64
--------------------------------------------------------------------------------
Diagnóstico Gold: gold_dataset_ia_municipio
Linhas: 23995
Colunas: 10

Duplicados:
0

Valores ausentes principais:
gap_meta                   18763
meta_alfabetizacao         18763
target_atingiu_meta        18763
ano                            0
id_municipio                   0
rede                           0
resultado_alfabetizacao        0
serie                          0
status_meta                    0
classificacao_risco            0
dtype: int64
--------------------------------------------------------------------------------
Distribuição status_meta:
status_meta
sem_meta_disponivel    18763
atingiu_meta            2788
abaixo_meta             2444
Name: count, dtype: int64

Distribuição classificação de risco:
classificacao_risco
sem_meta          18763
baixo_risco        2788
alto_risco         1066
atencao             773
risco_moderado      605
Name: count, dtype: int64

Gap meta:
count    5232.000000
mean        1.114841
std        15.201525
min       -68.900000
25%        -7.740000
50%         0.980000
75%        10.812500
max        84.270000
Name: gap_meta, dtype: float64